version: '3.8'

services:
  backend:
    image: deepsikder/chat-backend:v1
    container_name: chat_backend_prod
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    networks:
      - chat_network

  frontend:
    image: deepsikder/chat-frontend:v1
    container_name: chat_frontend_prod
    restart: always
    environment:
      VITE_API_URL: ${API_URL:-ws://localhost:8080}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
